# BIMBO v4.0 - Unified MongoDB for users + bans + settings + premium
import time
import logging
import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
from config import Config

logger = logging.getLogger(__name__)


class Database:
    def __init__(self, uri, db_name="BimboBotDB"):
        self._client = None
        self.db = None
        if not uri:
            logger.warning("⚠️  BIMBO_DATABASE_URL not set — using in-memory fallback.")
            self._fallback = {"users": {}, "bans": set(), "premium": {}, "thumbs": {}, "settings": {}, "streamlinks": {}}
            self._use_fb = True
            return
        try:
            self._client = AsyncIOMotorClient(uri, serverSelectionTimeoutMS=5000)
            self.db = self._client[db_name]
            self.users = self.db["users"]
            self.bans = self.db["bans"]
            self.premium = self.db["premium"]
            self.thumbs = self.db["thumbs"]
            self.settings = self.db["settings"]
            self.stats = self.db["stats"]
            # Stream links generated by /stream — auto-expire via TTL index
            self.streamlinks = self.db["streamlinks"]
            self._use_fb = False
            try:
                loop = asyncio.get_running_loop()
                loop.create_task(self.create_indexes())
            except RuntimeError:
                pass
        except Exception as e:
            logger.error(f"DB init error: {e}")
            self._use_fb = True
            self._fallback = {"users": {}, "bans": set(), "premium": {}, "thumbs": {}, "settings": {}, "streamlinks": {}}

    async def create_indexes(self):
        if self._use_fb:
            return
        try:
            await self.users.create_index("id", unique=True)
            await self.bans.create_index("id", unique=True)
            await self.premium.create_index("id", unique=True)
            await self.thumbs.create_index("id", unique=True)
            await self.settings.create_index("id", unique=True)
            await self.streamlinks.create_index("token", unique=True)
            # TTL index: MongoDB will auto-delete the doc when `expire_at`
            # (a datetime) is reached. expireAfterSeconds=0 => delete exactly
            # at the stored time. Yehi 1-din auto-delete ka kaam karta hai.
            await self.streamlinks.create_index("expire_at", expireAfterSeconds=0)
            logger.info("✅ Database indexes created successfully.")
        except Exception as e:
            logger.warning(f"Failed to create database indexes: {e}")

    async def add_user(self, user_id, name="", username=""):
        try:
            if self._use_fb:
                self._fallback["users"][user_id] = {"id": user_id, "name": name,
                                                     "username": username,
                                                     "joined": time.time()}
                return
            await self.users.update_one(
                {"id": int(user_id)},
                {"$setOnInsert": {"id": int(user_id), "join_date": time.time()},
                 "$set": {"name": name, "username": username,
                          "last_active": time.time()}},
                upsert=True
            )
        except Exception as e:
            logger.error(f"add_user: {e}")

    async def total_users(self):
        try:
            if self._use_fb:
                return len(self._fallback["users"])
            return await self.users.count_documents({})
        except Exception:
            return 0

    async def get_all_users(self):
        try:
            if self._use_fb:
                return list(self._fallback["users"].values())
            return self.users.find({})
        except Exception:
            return []

    async def delete_user(self, user_id):
        try:
            if self._use_fb:
                self._fallback["users"].pop(int(user_id), None)
                return
            await self.users.delete_one({"id": int(user_id)})
        except Exception as e:
            logger.error(f"del_user: {e}")

    # ---- BAN SYSTEM ----
    async def ban_user(self, user_id, reason=""):
        try:
            if self._use_fb:
                self._fallback["bans"].add(int(user_id))
                return
            await self.bans.update_one({"id": int(user_id)},
                                       {"$set": {"id": int(user_id), "reason": reason,
                                                 "banned_at": time.time()}},
                                       upsert=True)
        except Exception as e:
            logger.error(f"ban: {e}")

    async def unban_user(self, user_id):
        try:
            if self._use_fb:
                self._fallback["bans"].discard(int(user_id))
                return
            await self.bans.delete_one({"id": int(user_id)})
        except Exception as e:
            logger.error(f"unban: {e}")

    async def is_banned(self, user_id):
        try:
            if self._use_fb:
                return int(user_id) in self._fallback["bans"]
            return await self.bans.find_one({"id": int(user_id)}) is not None
        except Exception:
            return False

    async def ban_list(self):
        try:
            if self._use_fb:
                return list(self._fallback["bans"])
            return [u["id"] async for u in self.bans.find({})]
        except Exception:
            return []

    # ---- PREMIUM ----
    async def set_premium(self, user_id, expires_at, plan="premium"):
        try:
            if self._use_fb:
                self._fallback["premium"][int(user_id)] = {"id": int(user_id),
                                                           "expires": expires_at,
                                                           "plan": plan}
                return
            await self.premium.update_one({"id": int(user_id)},
                                          {"$set": {"id": int(user_id),
                                                    "expires": expires_at,
                                                    "plan": plan}},
                                          upsert=True)
        except Exception as e:
            logger.error(f"set_premium: {e}")

    async def remove_premium(self, user_id):
        try:
            if self._use_fb:
                self._fallback["premium"].pop(int(user_id), None)
                return
            await self.premium.delete_one({"id": int(user_id)})
        except Exception as e:
            logger.error(f"remove_premium: {e}")

    async def get_premium(self, user_id):
        try:
            if self._use_fb:
                return self._fallback["premium"].get(int(user_id))
            u = await self.premium.find_one({"id": int(user_id)})
            if u and u.get("expires", 0) > time.time():
                return u
            return None
        except Exception:
            return None

    # ---- THUMBNAIL ----
    async def set_thumb(self, user_id, file_id):
        try:
            if self._use_fb:
                self._fallback["thumbs"][int(user_id)] = file_id
                return
            await self.thumbs.update_one({"id": int(user_id)},
                                         {"$set": {"id": int(user_id), "file_id": file_id}},
                                         upsert=True)
        except Exception as e:
            logger.error(f"set_thumb: {e}")

    async def get_thumb(self, user_id):
        try:
            if self._use_fb:
                return self._fallback["thumbs"].get(int(user_id))
            d = await self.thumbs.find_one({"id": int(user_id)})
            return d["file_id"] if d else None
        except Exception:
            return None

    async def del_thumb(self, user_id):
        try:
            if self._use_fb:
                self._fallback["thumbs"].pop(int(user_id), None)
                return
            await self.thumbs.delete_one({"id": int(user_id)})
        except Exception as e:
            logger.error(f"del_thumb: {e}")

    # ---- SETTINGS per user ----
    async def set_user_setting(self, user_id, key, value):
        try:
            if self._use_fb:
                self._fallback["settings"].setdefault(int(user_id), {})[key] = value
                return
            await self.settings.update_one({"id": int(user_id)},
                                           {"$set": {key: value}}, upsert=True)
        except Exception as e:
            logger.error(f"set_setting: {e}")

    async def get_user_setting(self, user_id, key, default=None):
        try:
            if self._use_fb:
                return self._fallback["settings"].get(int(user_id), {}).get(key, default)
            d = await self.settings.find_one({"id": int(user_id)})
            return d.get(key, default) if d else default
        except Exception:
            return default

    # ---- STREAM LINKS (auto-expire in N hours via TTL) ----
    async def add_stream_link(self, token, url, user_id, ttl_hours=24, meta=None):
        """Store a generated stream link. Auto-deletes after ttl_hours."""
        import datetime
        now = time.time()
        expire_at = datetime.datetime.utcnow() + datetime.timedelta(hours=ttl_hours)
        doc = {
            "token": token,
            "url": url,
            "user_id": int(user_id),
            "created_at": now,
            "expire_at": expire_at,
            "meta": meta or {},
        }
        try:
            if self._use_fb:
                self._fallback.setdefault("streamlinks", {})[token] = {
                    **doc, "expire_ts": now + ttl_hours * 3600
                }
                return
            await self.streamlinks.update_one(
                {"token": token}, {"$set": doc}, upsert=True
            )
        except Exception as e:
            logger.error(f"add_stream_link: {e}")

    async def get_stream_link(self, token):
        """Return the stored link doc, or None if missing/expired."""
        try:
            if self._use_fb:
                d = self._fallback.get("streamlinks", {}).get(token)
                if not d:
                    return None
                if d.get("expire_ts", 0) < time.time():
                    self._fallback["streamlinks"].pop(token, None)
                    return None
                return d
            d = await self.streamlinks.find_one({"token": token})
            if not d:
                return None
            # Safety check in case TTL reaper hasn't run yet
            import datetime
            exp = d.get("expire_at")
            if exp and exp < datetime.datetime.utcnow():
                await self.streamlinks.delete_one({"token": token})
                return None
            return d
        except Exception as e:
            logger.error(f"get_stream_link: {e}")
            return None

    async def delete_stream_link(self, token):
        try:
            if self._use_fb:
                self._fallback.get("streamlinks", {}).pop(token, None)
                return
            await self.streamlinks.delete_one({"token": token})
        except Exception as e:
            logger.error(f"delete_stream_link: {e}")

    async def count_stream_links(self):
        try:
            if self._use_fb:
                return len(self._fallback.get("streamlinks", {}))
            return await self.streamlinks.count_documents({})
        except Exception:
            return 0

    async def incr_stat(self, key, amount=1):
        try:
            if self._use_fb:
                return
            await self.stats.update_one({"key": key},
                                        {"$inc": {"value": amount}},
                                        upsert=True)
        except Exception:
            pass

    async def get_stat(self, key):
        try:
            if self._use_fb:
                return 0
            d = await self.stats.find_one({"key": key})
            return d["value"] if d else 0
        except Exception:
            return 0


db = Database(Config.BIMBO_DATABASE_URL)
